# Generated by Django 5.0.4 on 2024-04-03 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='sections',
            new_name='section',
        ),
    ]
