# Generated by Django 5.0.4 on 2024-04-05 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_sections_task_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed', 'priority']},
        ),
    ]
