# Generated by Django 5.2.4 on 2026-03-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed', 'priority', 'goal_date', 'goal_time']},
        ),
    ]
